Todo app
storres20/M3W2-reactTodoApp pull request #1
Opened 2022-12-06 21:07 UTC by storres20

# In this milestone I did the following activities:
- I add "todo-app" branch
- I use React js
- I add style modules
- I add css styles
- I add components for navbar, header, others
- I add uuid
- I checked the linters
- I add Readme file
- [Part 1 - React tutorial: The beginner's guide to learning React in 2020](https://ibaslogic.com/react-tutorial-for-beginners/).
- [Part 2 - Working with React form and handling event](https://ibaslogic.com/react-form-handling/).
- [Part 3 – How to implement CSS in Reactjs app](https://ibaslogic.com/css-in-reactjs-app/).
- [Part 4 – How to edit to dos items](https://ibaslogic.com/how-to-edit-todos-items-in-react/).
- [Part 5 – Persisting React state in local storage](https://ibaslogic.com/persisting-react-state-in-local-storage/) (Optional).
- [Part 6 – Getting started with React lifecycle methods](https://ibaslogic.com/react-lifecycle-methods/).
- [Part 7 – Getting started with React hooks](https://ibaslogic.com/react-hooks-tutorial/).
- [Part 8 – How to use SVG icons in React](https://ibaslogic.com/how-to-use-svg-icons-in-react-project/) (Optional).
- [Part 9 – Routing with React Router](https://ibaslogic.com/routing-with-react-router/).
- [Part 10 – How to add hamburger menu in React](https://ibaslogic.com/how-to-add-hamburger-menu-in-react/) (Optiona).
- [Part 11 – Deploying React app to GitHub Pages](https://ibaslogic.com/deploying-react-app-to-github-pages/) (Optional).

2022-12-06 23:59 UTC, Boku52500 commented on src/index.js
> -import reportWebVitals from './reportWebVitals';
You must have an error in one of those imports or paths, because the page is blank. Please fix this, so everyone is able to see your project.

2022-12-07 00:00 UTC, Boku52500 requested changes
Hi @storres20  ,
 
 Good job so far! There are some issues that you still need to work on but you are almost there!
 
 ## Highlights 
 * [x]  All linter checks are passing
 * [ ]  Descriptive Readme file
 * [ ]  Descriptive pull request title and summary
 * [ ] Good use of hooks
 
 ![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif) [ ](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)
 
 ## Required Changes 
 _Check the comments under the review._
 
 ## Optional suggestions
_Check the comments under the review._

 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
 You can also consider:
 
 Cheers and Happy coding!clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

2022-12-07 00:05 UTC, Boku52500 commented on src/index.js
> -import reportWebVitals from './reportWebVitals';
You must have an error in one of those imports or paths, because the page is blank. Please fix this, so everyone is able to see your project.

2022-12-07 00:12 UTC, Boku52500 commented on src/components/InputTodo.js
> +/* eslint-disable no-alert */
(OPTIONAL) Consider removing these linter disabling lines from code. It will make your project look more professional.

2022-12-07 00:14 UTC, storres20 commented
Dear code reviewer
I've fixed all issues
thanks for your suggestions

2022-12-07 00:23 UTC, Boku52500 approved these changes
### Hi @storres20 

 Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations!

 [ ](https://user-images.githubusercontent.com/69077061/200411711-6e741427-6e46-4354-932f-f1445ecc09bd.gif) ![68747470733a2f2f6669636f666f72756d732e6d796669636f2e636f6d2f74352f696d6167652f736572766572706167652f696d6167652d69642f343932363069463839303835363833444139334135422f696d6167652d73697](https://user-images.githubusercontent.com/69077061/200411711-6e741427-6e46-4354-932f-f1445ecc09bd.gif) [ ](https://user-images.githubusercontent.com/69077061/200411711-6e741427-6e46-4354-932f-f1445ecc09bd.gif)
 
 ## Highlights
* [ ]   Correct GitHub Flow 
* [ ]   Good commit history
* [ ]   Good PR title/description
* [ ]   All linters passed
 
## Optional suggestions
_Check the comments under the review._

 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
 
Cheers and Happy coding!
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

2022-12-07 00:23 UTC, Boku52500 commented on src/components/InputTodo.js
> +/* eslint-disable no-alert */
(OPTIONAL) Consider removing these linter disabling lines from code. It will make your project much more professional.

2022-12-07 00:27 UTC, merged